Description:
  A set of resources used by the EC2 Playground

Parameters:
  DefaultVPC:
    Type: String
    Default: ""

  CidrBlock:
    Type: String
    Default: 10.0.0.0/20

  BucketNameBase:
    Type: String

Conditions:
  CreateVPC: !Equals
    - !Ref DefaultVPC
    - ""

Resources:
  VPC:
    Condition: CreateVPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      Tags:
        - Key: Name
          Value: ec2-playground
        - Key: props
          Value: undefined

  IGW:
    Condition: CreateVPC
    Type: AWS::EC2::InternetGateway

  VPC2Internet:
    Condition: CreateVPC
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref IGW
      VpcId: !Ref VPC

  IPv6Cidr:
    Condition: CreateVPC
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref VPC

  Subnet:
    Condition: CreateVPC
    Type: AWS::EC2::Subnet
    DependsOn: IPv6Cidr
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref CidrBlock
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select
        - 0
        - !Cidr
          - !Select [0, !GetAtt VPC.Ipv6CidrBlocks]
          - 1
          - 64

  RouteTable:
    Condition: CreateVPC
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  SubnetRTAssociation:
    Condition: CreateVPC
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref Subnet

  RouteIPv4:
    Condition: CreateVPC
    Type: AWS::EC2::Route
    DependsOn:
      - VPC2Internet
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTable

  RouteIPv6:
    Condition: CreateVPC
    Type: AWS::EC2::Route
    DependsOn:
      - VPC2Internet
    Properties:
      DestinationIpv6CidrBlock: ::/0
      GatewayId: !Ref IGW
      RouteTableId: !Ref RouteTable

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !If
        - CreateVPC
        - !Ref VPC
        - !Ref DefaultVPC
      GroupDescription: EC2Playground
      SecurityGroupEgress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: -1
        - CidrIpv6: ::0/0
          IpProtocol: -1
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketNameBase}-${AWS::AccountId}-${AWS::Region}'

  InstancePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AWS::StackName}-InstancePolicy-${AWS::Region}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub 'arn:aws:s3:::${Bucket}/*'
          - Effect: Allow
            Action:
              - s3:ListBucket
            Resource:
              - !GetAtt Bucket.Arn
          - Effect: Allow
            Action:
              - ec2:CreateTags
            Resource: "*"
            Condition:
              StringLike:
                aws:UserId: "*:${ec2:InstanceID}"

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-InstanceRole-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
      ManagedPolicyArns:
        - !Ref InstancePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-InstanceProfile-${AWS::Region}'
      Roles:
        - !Ref InstanceRole

  CmdNotification:
    Type: AWS::SNS::Topic

  CmdNotificationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ssm.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: publish-sns
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sns:Publish
                Resource: !Ref CmdNotification

  CmdNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt CmdNotificationQueue.Arn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref CmdNotification
    DependsOn:
      - CmdNotificationQueuePolicy

  CmdNotificationQueue:
    Type: AWS::SQS::Queue

  CmdNotificationQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: sqs:SendMessage
            Principal:
              Service: sns.amazonaws.com
            Resource: !GetAtt CmdNotificationQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !Ref CmdNotification
      Queues:
        - !Ref CmdNotificationQueue

Outputs:
  SecurityGroup:
    Value: !Ref SecurityGroup

  Subnet:
    Condition: CreateVPC
    Value: !Ref Subnet

  InstancePolicy:
    Value: !Ref InstancePolicy

  InstanceProfile:
    Value: !Ref InstanceProfile

  Bucket:
    Value: !Ref Bucket

  CmdNotification:
    Value: !Ref CmdNotification

  CmdNotificationQueue:
    Value: !Ref CmdNotificationQueue

  CmdNotificationRole:
    Value: !GetAtt CmdNotificationRole.Arn
